project:
  type: book
  output-dir: docs



book:
  title: "dicopal"
  author: "Thomas Camminady"
  date: "7/6/2023"
  chapters:
    - index.qmd
    - part: Sources.qmd
      chapters:
        - notebooks/cartocolors.qmd
        - notebooks/cmocean.qmd
        - notebooks/colorbrewer.qmd
        - notebooks/lightbartlein.qmd
        - notebooks/matplotlib.qmd
        - notebooks/mycarta.qmd
        - notebooks/scientific.qmd
        - notebooks/tableau.qmd
        - notebooks/wesanderson.qmd
        - notebooks/otakeito.qmd
    - part: types.qmd
      chapters:
        - notebooks/sequential.qmd
        - notebooks/diverging.qmd
        - notebooks/qualitative.qmd
  page-navigation: false



format:
  html:
    theme:
      light: flatly
      dark: darkly
    page-layout: full
    code-fold: true
    code-overflow: wrap
    toc: true
    toc-expand: 10
    toc-depth: 10

