project:
  type: book
  output-dir: docs



book:
  title: "A collection of colors"
  author: "Thomas Camminady"
  date: "7/6/2023"
  chapters:
    - index.qmd
    - part: Sources.qmd
      chapters:
        - notebooks/cartocolors.qmd
        - notebooks/cmocean.qmd
        - notebooks/colorbrewer.qmd
        - notebooks/lightbartlein.qmd
        - notebooks/matplotlib.qmd
        - notebooks/mycarta.qmd
        - notebooks/scientific.qmd
        - notebooks/tableau.qmd
        - notebooks/wesanderson.qmd
        - notebooks/otakeito.qmd
        - notebooks/apdocc.qmd
    - part: types.qmd
      chapters:
        - notebooks/sequential.qmd
        - notebooks/diverging.qmd
        - notebooks/qualitative.qmd
  page-navigation: false



format:
  html:
    anchor-sections: true
    theme:
      light: [flatly,custom.scss]
      dark: [darkly,custom.scss]

    page-layout: full
    code-fold: true
    code-copy: true
    highlight-style: github

    code-line-numbers: false
    code-overflow: scroll
    toc: false
    toc-expand: 10
    toc-depth: 10

execute:
  cache: true
